# Please set your consumer key and cunsumer secret,
# and rename the file name to "twitter.yml".

consumer_key: 
consumer_secret:

# This is optional, but it is recommended to specify
# the Twitter ID. The OAuth callback will be validated,
# if this Twitter account was used.
#
#twitter_id:
